baseURL = 'https://nureon22.github.io/flexy-components/'
languageCode = 'en-us'
title = 'Flexy Components Documentation'
[markup]
  [markup.highlight]
    tabwidth = 2
    noClasses = false
[params]
  repository = "https://github.com/nureon22/flexy-components"
  goatcounter = "https://nureon22.goatcounter.com/count"
  google_site_verification = "CtHwtf8ha6XoGf3CgvjlCz9gSec5qHVj0X1C_ImnGl0"

  [params.author]
    name = "Phyo Wai Lin"
    url = "https://github.com/nureon22"
    email = "phyowailin2004@proton.me"

  [params.project]
    license = 'MIT'
