baseURL = 'https://nureon22.github.io/flexy-components/'
languageCode = 'en-us'
title = 'Flexy Components Documentation'
enableGitInfo = true
[markup]
  [markup.highlight]
    codeFences = false
[params]
  repository = "https://github.com/nureon22/flexy-components"
  umami_id = "0cff7e01-0025-4eb7-823b-bd7ef61ca158"
  google_site_verification = "CtHwtf8ha6XoGf3CgvjlCz9gSec5qHVj0X1C_ImnGl0"

  [params.author]
    name = "Phyo Wai Lin"
    url = "https://github.com/nureon22"
    email = "phyowailin2004@proton.me"

  [params.project]
    license = 'MIT'
